# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ronitz
# "service" is the name of this project. This will also be added to your AWS resource names.
service: insertlambda

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1

functions:
  insertSong:
    handler: handler.insertSongLambda
